# Discussion {#discussion}

For over 80 years scientists have been trying to explain the presence of $\theta$ oscillations in the brain [@berger_uber_1929; @jung_method_1938], attempting to identify potential locations responsible for generating such activity [@petsche_significance_1962]. To date, we still do not completely understand the exact function of these oscillations [@buzsaki_theta_2002; @colgin_mechanisms_2013; @muller_septohippocampal_2018]. However, significant steps towards understanding interactions between areas and cells have been achieved and multiple targets identified to gain further insights into $\theta$ function and generation [@dragoi_interactions_1999; @gaykema_cortical_1990; @gonzalez-sulser_gabaergic_2014; @rawlins_septo-hippocampal_1979; @swanson_connections_1979]. Since one of the important regions for $\theta$ rhythm generation is the MS, I addressed the question of whether the PaS -- a formerly, relatively unexplored member of the parahippocampal circuit region which exhibits strong $\theta$ oscillatory activity *in-vivo* [@ebbesen_cell_2016; @tang_functional_2016] and on a cellular level [@glasgow_conductances_2008] -- receives projections from the MS. Due to the PaS contributing major excitatory inputs to the MEC, it is well-positioned to relay oscillatory excitation controlled through the MS.

I focused on two groups of septal cells which play an important role in $\theta$ generation in the hippocampus and MEC and are, thus, potentially crucial for the PaS. Hence, we recorded and classified cells in the PaS *in-vitro* to map connections from MS PV^+^ and MS ChAT^+^ cells. In addition to this descriptive account of cellular physiology and in order to establish the potential impact of septal connections in mediating the oscillatory activity, I then investigated network activity in head-fixed awake mice *in-vivo* and quantified the effects of modulating septal projections on the LFP. I estimated parameters of measurements using Bayesian hierarchical models [@gelman_multilevel_2006] to account for nested structures which generally occur in such an experimental design. Additionally, this approach is less likely to negatively bias the reader and overcomes caveats associated with *p*-values commonly used in papers [@buchinsky_p_2017; @makowski_indices_2019].

## Interneurons have distinct cell properties

Until recently, descriptions of PaS cells *in-vitro* in the literature were mainly based on morphology [@funahashi_presubicular_1997]. In our study, we classified cells in the parasubiculum on a larger scale using electrophysiological properties, immunohistochemistry and clustering approaches [@sammons_electrophysiological_2019]. In the present study, I therefore employed the same tools including hierarchical clustering to generate three cell type clusters based on previous data. I then split layer I cells as a separate group and verified that they, indeed, had distinct cell properties. I found that, even when a targeted approach to record interneurons is used, a large proportion of cells is still part of the putative pyramidal cell cluster [@sammons_electrophysiological_2019]. This group of cells makes up $80\%$ of the PaS population and is the major contributor to the glutamatergic output of the PaS. However, an important observation I made is that of the distinction of regular slow firing interneurons in layer II of the PaS and interneurons in layer I. The two groups were previously characterised as one group [@sammons_electrophysiological_2019], however, IN-L1 cells emerged to be significantly different in major parameters such as firing frequency, FWHM, $C_{m}$ and the slopes of the action potential (Figure \@ref(fig:APPropertyPlot)). This suggests that action potential dynamics might be distinct from other interneurons and can potentially lead to different computational consequences. One possible advantage of these dynamics could be that a wider action potential can lead to an increase of presynaptic Ca^2+^ concentration, leading to a more reliable transmission [@geiger_dynamic_2000]. A relatively low rheobase and an almost instantaneous initiation of firing upon stimulation could reliably relay information to downstream partners, which might make IN-L1 cells an important part of the local network (see for rheobase and latency Table \@ref(tab:CellParTable)).

In contrast, FS cells showed a much higher maximum firing frequency, which is in line with the behaviour of PV^+^ interneurons in the PaS, PrS and MEC [@martinez_anatomical_2017; @nassar_diversity_2015; @sammons_electrophysiological_2019]. FS cells generally had to be more depolarised to initiate spiking, but could sustain a continuously high firing rate. Recently, it has been shown that the PaS is the area with the highest density of PV^+^ cells in the whole mouse brain [@bjerke_densities_2021]. This underlines the importance and potential influence of this cell type in the region. Due to the inhibition of the local network, which can be mediated by FS spiking cells and the high connectivity of PV^+^ interneurons [@fuchs_local_2016; @hangya_gabaergic_2009; @roux_vivo_2014; @stark_inhibition-induced_2013] as found in the MEC and hippocampus, I hypothesised that FS cells could be preferential targets for disinhibition through PV^+^ MS cells. This could potentially release a "brake" in the parahippocampal circuitry and drive $\theta$ oscillations.

## PV^+^ connections to the PaS

In addition to the classification of these cells *in-vitro*, I also employed an optogenetic approach to understand interactions between the MS and PaS. To do so, cells were recorded in whole-cell configuration in slices and ChR2 expressing fibres were activated using short light pulses. Measuring connections from the MS to PaS in PV-Cre mice, we could demonstrate that previously reported anatomical projections indeed make functional connections [@unal_synaptic_2015; @tang_functional_2016]. @unal_synaptic_2015 found that the PV^+^ fibre density was highest in the PaS, compared to the hippocampus or other parahippocampal regions, and made putative contacts to parasubicular PV^+^ cells and CB^+^ cells. CB was previously identified as having strong overlap with PV^+^ neurons in the PaS and is mainly a marker for local GABAergic cells [@sammons_electrophysiological_2019].

We presented evidence that interneurons indeed constitute most of the functional connections confirming previous morphological evidence (Figure \@ref(fig:PVConnectivity)). Furthermore, we could show that the proportion of cells being inhibited by GABAergic inputs was the highest in FS interneurons, which most likely represents a large proportion of parasubicular PV^+^ and CB^+^ interneurons [@sammons_electrophysiological_2019]. Other studies established an important role of FS cells in $\theta$ modulation in the MEC and hippocampus [@amilhon_parvalbumin_2015] and found PV^+^ cells in the hippocampus and cortex to orchestrate spike timing during $\theta$ phases [@roux_vivo_2014; @stark_inhibition-induced_2013]. The high connectivity of FS cells in the PaS is striking and in line with previous studies investigating septal projections to the MEC or hippocampus where PV^+^ fibres preferentially target PV^+^ fast spiking interneurons leading to disinhibition of the local network [@fuchs_local_2016; @gonzalez-sulser_gabaergic_2014; @melzer_long-rangeprojecting_2012]. Based on recent local connectivity data of pyramidal cells and interneurons in the PaS [@sammons_local_2021], it can be proposed that an inhibition of FS cells through the MS will also lead to a reduced inhibition of pyramidal cells in the PaS. The high connectivity and recurrent connection scheme between FS and pyramidal cells suggest that the PaS is well-positioned to generate oscillatory network activity. Given the high firing rate of FS cells, a reduction of FS spiking can lead to a release of strong local inhibition of the network. As I have shown, the inhibition of spiking and entraining of frequencies via septal fibre stimulation in interneurons suggests that local $\theta$ entrainment via interneurons could be possible and effective (Figure \@ref(fig:PhaseLockInVitroPlot)). Furthermore, our data shows that regular firing interneurons were also targets of septal PV^+^ cells increasing disinhibition of the network and further allowing DS to be active. A similar proportion of cells was found to be inhibited in the MEC [@fuchs_local_2016; @gonzalez-sulser_gabaergic_2014], further supporting the notion that PV^+^ MS projections follow common targeting schemes in the cortex.

To our surprise, IN-L1 cells were inhibited by the activation of PV^+^ fibres, a connection not reported in previous studies investigating MS PV^+^ projections. Due to the position of IN-L1 cells in cortical circuits, this novel connection could have significant new implications for the network. It has been shown in the somato-sensory and visual cortex of rats and mice that layer I interneurons exhibit recurrent connections to pyramidal cells of layer II and III, broadly inhibit a vast majority of layer II and III interneurons and are highly interconnected [@jiang_principles_2015; @olah_output_2007; @wozny_specificity_2011]. This places them in a central position where they can inhibit a whole interneuron network while also modulating pyramidal cell activity. Whether or not we have similar connectivity schemes outside of known sensory cortices in the PaS or MEC remains unknown. This open question could provide important information about the workings of septal-parahippocampal interactions. Combining these results, I hypothesise that septal PV^+^ cells contribute to an accurately timed inhibition of interneurons, which leads to an increase in DS firing while background activity -- not synchronised inputs -- might be reduced through IN-L1 cells regulating the overall inhibition (Figure \@ref(fig:ProjectionScheme)A). Overall, the increase in DS activity through disinhibition from septal PV^+^ cells will increase excitatory output to the MEC [@canto_all_2012] and relay information to entorhinal pyramidal cell clusters known for their spatial coding [@tang_functional_2016]. Consequently, excitation from the PaS could drive grid-cells in the MEC and synchronise other behaviourally relevant cells across the parahippocampal network. It is not known whether or not the PaS receives distinct inputs from the MS which are integrated in the parahippocampal network independently of other regions. Studies investigating projection patterns using juxta-cellular recordings provided evidence that MS PV^+^ orchid cells can simultaneously target MEC and PrS cells, although, none of the cells projected to the PaS [@viney_shared_2018]. A failure to detect common projections could arise due to the limited number of cells which can be labelled using the juxta technique or suggest, given the high density of projections to the PaS, that the PaS is targeted by a different cell group which exclusively and with high divergence inhibits the PaS or other structures. Answering this question could lead to a better understanding of how MS inhibitory signals are integrated in the parahippocampal network and could elicit new questions for the future.

```{r ProjectionScheme, fig.scap='(ref:ProjectionShortScheme)', fig.cap = '(ref:ProjectionScheme)',fig.show='hold', fig.align='center',echo=FALSE, fig.width=10, fig.height=4, dpi=600}
#PVScheme  <- readPNG(source = "/alzheimer/Daniel_Data/R/Thesis/Figures/Schemes/PVScheme.png", native = T)
#ChATScheme  <- readPNG(source = "/alzheimer/Daniel_Data/R/Thesis/Figures/Schemes/ChATScheme.png", native = T)
PVScheme  <- wrap_elements(cowplot::ggdraw()+cowplot::draw_image(magick::image_read("Figures/Schemes/ConnectSchemeSimplePVthick.png",density = 600), interpolate = F)) + ggtitle("PV") + theme(plot.title = element_text(hjust = 0.5, size = 22))
ChATScheme  <- wrap_elements(cowplot::ggdraw()+cowplot::draw_image(magick::image_read("Figures/Schemes/ConnectSchemeSimpleChATthick.png",density = 600), interpolate = F)) + ggtitle("ChAT") + theme(plot.title = element_text(hjust = 0.5, size = 22))


# PVScheme <- wrap_elements(PVScheme, clip = T) + ggtitle("PV") + theme(plot.title = element_text(hjust = 0.5, size = 25))
# ChATScheme <- wrap_elements(ChATScheme, clip = T) + ggtitle("ChAT") + theme(plot.title = element_text(hjust = 0.5, size = 25))

PVScheme + ChATScheme +  plot_annotation(tag_levels = "A") + plot_layout(widths = c(1,1)) &
  theme(plot.tag = element_text(size=16))
```

<!-- - Given our data, the structure and network scheme of the PaS it could play a crucial role in relaying oscillatory activity to the MEC mediated by the MS. -->

<!-- - Recently, it was shown that local parasubicular interneurons are likely to project to WFS1 cells (fast spiking interneurons: 44%; not fast spiking interneurons: 13%) whilst receiving glutamergic inputs from WFS1 cells with a high probability (fast spiking interneurons: 23%; not fast spiking interneurons: 2.6%) [@sammons_local_nodate]. This feedback circuit sets up the PaS as a oscillatory network. -->

## ChAT^+^ connections to the PaS

Cholinergic projections to the parahippocampal network have been proposed to play an important role in learning and memory and are implicated in $\theta$ generation [@heys_effects_2012]. One of the main regions to provide such cholinergic innervation is the MS [@zaborszky_specific_2018] and lesioning specifically cholinergic MS neurons using a selective neurotoxin (IgG192-Saporin -- SAP) will lead to the impairment of spatial working memory [@johnson_selective_2002; @robinson_192igg-saporin_1996; @walsh_injection_1996]. But it should be noted that lesions using SAP do not achieve a complete reduction of acetylcholine activity [@chang_impaired_2004]. Such strong effects motivated us to look into the targets of MS ChAT^+^ projections to the PaS. To map connections, we used an optogenetic approach specifically targeting ChAT^+^ fibres from MS cells and measured synaptic responses in the PaS *in-vitro*.

Strikingly, ChAT^+^ connections mostly targeted superficial cells by depolarising them. This is in line with previous findings in the MEC [@desikan_target_2018], where the connectivity was similar and mainly showed depolarisations of IN-L1 cells as well \@ref(fig:ChATConnectivity)). A common pattern could mean that cholinergic activation increases the activity of layer I interneurons in the parahippocampal network and mediates local inhibition. Slow depolarisations of IN-L1 cells could lead to increased activity and, in combination with GABAergic inhibition of IN-L1 through PV^+^ fibres, synchronise spike timing. Given that the activity of cholinergic cells in the MS and acetylcholine release is related to movement and behaviour [@dudar_release_1979; @nilsson_acetylcholine_1990], it could result in an increased involvement of superficial interneurons during such behaviours. This could be an important mechanism for network modulation which might also be found in the MEC in the future. The result of such a combined effect would provide evidence for an important link between layer I interneuron activation and behavioural states [@ma_firing_2020; @vandecasteele_optogenetic_2014]. A substantial proportion of layer I cells in the MEC have been shown to display GABA~A~R responses [@desikan_target_2018]. I did not observe such a fraction of hyperpolarisations in the ChAT^+^ data. However, a larger sample of layer I cells could reveal similar proportions in the future. Generally, amplitudes of de- and hyperpolarisations were small in all cell types (Figure \@ref(fig:ChATAmplitude)A and D), but still large enough to indicate that cholinergic receptors were active. Hence, different muscarinic mechanisms which were not detected in this study could effect PaS network activity [@caruana_stimulation_2004; @glasgow_conductances_2008; @glasgow_local_2007].

In particular, FS cells were similarly likely to be connected responded in most of the cases by hyperpolarisation, suggesting a complementary mechanism to MS PV^+^ mediated inhibition. Therefore, inhibition of FS cells in the PaS and MEC via MS ChAT^+^ cells seems to follow similar rules to previously mentioned PV^+^ projections. The inhibition through cholinergic fibres could reduce membrane potential of FS cells enough to enable PV^+^ cells in the MS to more efficiently inhibit FS cells with an increased success rate. In comparison, $25\%$ of the PaS IN clusters were affected through depolarisation, hyperpolarisation or both simultaneously. Cells of the IN cluster represent a heterogeneous population expressing somatostatin, reelin and calbindin. This could potentially explain diverse responses to ChAT^+^ MS fibre stimulation [@sammons_electrophysiological_2019]. In contrast to data from the MEC, I did not detect a high response rate for ChAT^+^ fibres stimulation in pyramidal cells [@desikan_target_2018]. Whereas MEC pyramidal cells depolarise in $40\%$ of the cases upon ChAT^+^ fibre stimulation [@desikan_target_2018], I could only detect a small fraction of $3$ to $14\%$ in DS cells. However, given the cell density of DS cells in the PaS, it could still reflect a substantial amount of affected cells with potentially large network effects. Previous studies have shown that the pronounced sag potentials of cells in the MEC are $I_{h}$ mediated and can be modulated by carbachol an agonist for nicotinic and muscarinic receptors [@sparks_contribution_2014]. Analogous to the MEC cells, PaS pyramidal cells have similar sag-properties which are mediated by $I_{h}$ suggesting the possibility of similar mechanisms [@glasgow_conductances_2008]. Considering that the probability of direct effects on hyper- or depolarisation in parasubicular DS cells after MS cholinergic stimulation was low,, it is possible to envisage an effect which reduces $I_{h}$ conductance and, therefore, subtly modulates the intrinsic properties of the cell [@alonso_differential_1993; @heys_neuromodulation_2012; @pastoll_intrinsic_2012] such as the intrinsic oscillatory frequency [@giocomo_time_2008]. Reaching high enough acetylcholine concentrations using fibre stimulation, however, can be challenging *in-vitro* due to circulating ACSF. A potential result of such a modulation can be observed in the MEC when activating a sustained release of acetylcholine from the MS by releasing acetylcholine from cholinergic fibres using a chemogenetic approach in freely behaving mice [@carpenter_modulating_2017]. An increase in acetylcholine will slightly decrease the $\theta$ frequency peak without changing the power. Cholinergic cells in the MS seem to be dependent on the behavioural state and an artificial activation will, for example, only lead to changes when the animal is anaesthetised or the network in an inactive state [@mamad_medial_2015; @vandecasteele_optogenetic_2014]. However, @vandecasteele_optogenetic_2014 have shown that the activation of cholinergic cells during a low activity state, will not lead to an entrainment of $\theta$ in the hippocampus but rather increase power at the already occurring $\theta$ frequency band. In contrast, running animals will not show power changes using the same stimulation due to potentially increased cholinergic activity.

A different effect of an increase in acetylcholine in the PaS and MEC, is a reduction in amplitude of excitatory inputs combined with an increased facilitation allowing for enhanced temporal summation of inputs, which is especially efficient at $\gamma$-frequency [@glasgow_cholinergic_2012; @sparks_contribution_2014]. Such a mechanism could potentially prime PaS pyramidal cells for synaptic modification through increased acetylcholine concentration during MS mediated $\theta$ and, therefore, strengthen relevant synchronously occurring inputs to the MEC and PaS, as was previously shown in the hippocampus [@huerta_bidirectional_1995]. Evidence to support the hypothesis that the MS could contribute to such an acetylcholine increase was presented by @hamam_cholinergic_2007, who have shown that facilitation of inputs mediated by muscarinic receptors in the MEC is larger during movement as opposed to an immobile state. Additionally, @dudar_release_1979 recorded an increase of hippocampal acetylcholine concentration during running phases and were able to abolish the increase by lesioning the septal area. Furthermore, a block of muscarinic receptors will lead to a reduced speed-$\theta$ relationship in the MEC and, more importantly, change the coupling of $\theta$ nested $\gamma$ in the MEC and hippocampus [@hentschke_muscarinic_2007; @newman_cholinergic_2013]. Given the strong excitatory output of the PaS to the MEC, improved temporal summation could occur during $\theta$ nested $\gamma$ cycles and play an important role in memory formation [@huerta_bidirectional_1995].

(ref:ProjectionShortScheme) Schematic of PaS network for PV^+^ and ChAT^+^ inputs 
(ref:ProjectionScheme) **Schematic of PaS network for PV^+^ and ChAT^+^ inputs.** The connectivity scheme for inputs from the MS. Arrows indicate the effect of MS inputs onto cells. Red cells represent FS cells, pink IN cells, turquoise IN-L1 cells, and blue DS cells. Synapses are represented as circles for excitatory or cholinergic synapses and lines for inhibitory GABAergic synapses. Local IN-L1 connectivity is not yet confirmed in the PaS and is informed from studies in other cortical areas [@jiang_principles_2015; @olah_output_2007; @wozny_specificity_2011]. Septal fibres are presented in green and arrows indicate the MS input effect on the target cells (up +/down -/both ±). DS cells project to the MEC and have local recurrent connections. The black line at the bottom indicates the pial surface. Cells connecting to themselves do not necessarily represent autaptic connections to a single cell but cell type connections to the same cell type. (A) shows the scheme for PV^+^ MS fibres and (B) the corresponding scheme for ChAT^+^.

Taken together, this suggests the importance of MS cholinergic projections, especially during behavioural states via the activation of layer I interneurons and disinhibition of the PaS through FS cells, but also a potential impact on memory formation and strengthening of connections through synaptic facilitation.

## *In-vivo* MS PV^+^ activation

### MS stimulation drives LFP

Based on the target projection profile of MS PV^+^ fibres to the PaS, I designed an experiment in awake mice to establish whether the LFP of the PaS can be modulated by MS intervention. Further, I wanted to investigate whether the different anatomical structure of the PaS, in comparison to the MEC, results in different LFP properties during fibre stimulation [@sammons_electrophysiological_2019; @tang_functional_2016; @witter_architecture_2014]. The density of pyramidal cells and the organised structure of pyramidal dendrites in the PaS suggests that LFP responses could be pronounced due to alignment [@herreras_local_2016].

Stimulating septal cells in the MS directly led to a drastic increase in power at the stimulation frequency in the PaS (Figure \@ref(fig:PowerDensityNested)). The power increase was also positively dependent on the stimulation, which meant that a higher stimulation frequency increased power more in relation to the baseline (Figure \@ref(fig:PSDModelFrequency)B). However, differences in power between MEC and PaS were not detected. This suggests that the dendritic organisation did not contribute significantly or that LFP signal was potentially equal due to volume conductance [@kajikawa_how_2011]. Future, current source density analysis could address a possible volume conductance and lead to more insights into PaS-MEC interactions.

Similarly, phase locking was strong over a wide range of stimulation frequencies, suggesting that stimulation synchronised the network reliably (Figure \@ref(fig:SpectrumRhoNested)). Even at the maximum tested $32\ Hz$ stimulation, phase locking was high in the PaS and MEC. Recent findings in $Pvalb^{Cre}$ rats showed that direct cell stimulation can also lead to strong entrainment of the stimulation frequency in freely moving animals and even abolish naturally occurring $\theta$ [@lepperod_optogenetic_2021]. A stimulation of up to $32\ Hz$ still produced reliable entrainment, as also shown by @lepperod_optogenetic_2021. I, however, observe a reduction in natural occurring $\theta$, which could be due to very low power in $\theta$ frequencies during immobility (Figure \@ref(fig:PowerDensityNested)) [@mcfarland_relationship_1975; @vanderwolf_hippocampal_1969]. The MS stimulation led to a synchronisation of the local MS network but also likely synchronised activity in the hippocampus [@etter_optogenetic_2019] which could provide excitation to the MEC and PaS [@rowland_transgenically_2013; @van_groen_connections_1990; @zhang_optogenetic_2013].

### Fibre stimulation fails to drive LFP

Stimulating the fibre terminals in the PaS and MEC failed to induce changes compared to the MS stimulation alone. In contrast, other studies were able to produce LFP changes when stimulating terminals in the MEC of freely moving rats and mice [@lepperod_optogenetic_2021; @schlesiger_two_2021]. In moving animals, PV^+^ fibres of the MS seemed to be sufficient to drive LFP responses, even though with slightly weaker magnitude. This suggests that a higher baseline activity in the network is required and can, thus, be modulated by fibre stimulation alone. Hence, the difference between immobile animals and running animals can be described as an excitatory drive through movement.

The behavioural state of an animal for $\theta$ was shown to have significant consequences for the experimental paradigm [@mamad_medial_2015; @vandecasteele_optogenetic_2014]. A potential origin for excitatory drive was presented by @justus_glutamatergic_2017 who showed that during locomotion glutamatergic fibres of the MS projecting to the MEC are active and increase activity when the animal increases speed. Another study was able to initiate movement of the animal by stimulating the MS directly via glutamatergic cells directly, and could entrain the LFP response in the hippocampus [@fuhrmann_locomotion_2015]. However, such an entrainment was abolished when a glutamate blocker was applied in the MS to shut down local transmission strengthening the evidence for the importance of GABAergic projecting neurons for $\theta$ long-range entrainment. It also underlines the important role for $VGluT2$ (glutamatergic) cells in the local MS circuit rather than increasing excitation in distant areas. Similar findings have been produced by @robinson_optogenetic_2016 who could induce entrainment in $VGluT2-Cre$ mice only when stimulating MS cells locally and failed when stimulating the fibres. Septal glutamatergic cells were proposed to synchronise local activity in the MS and, therefore, drive GABAergic and cholinergic cell activation targeting the hippocampus [@robinson_optogenetic_2016], which in turn can provide excitation to the parahippocampal network. Activation of cholinergic cells in the MS increases power in the $\theta$ and $\gamma$ band of anaesthetised mice [@vandecasteele_optogenetic_2014] providing another alternative mechanism. As mentioned in the previous section, running could elevate the concentration of acetylcholine [@dudar_release_1979], setting up the network for interneuron interventions which can entrain frequencies. In my case, a lack of local excitation in the PaS (Figure \@ref(fig:OverViewInVivo)E) could mean that PV^+^ fibre activation is not sufficient to induce LFP changes and, therefore, entrainment. In contrast, freely moving animals will exhibit increased activity through cholinergic activation, but also exhibit more activity of the MS during locomotion. Interestingly, @lepperod_optogenetic_2021 shows that activation of PV^+^ fibres will disrupt phase precession, suggesting the importance of PV^+^ cells for setting spike timing in the MEC. However, @schlesiger_two_2021 could not detect a change of phase precession by PV^+^ fibre stimulation but, instead, found CB^+^ cells of the septum to be most important for setting the phase of spiking in the MEC. Previously, septal CB^+^ were found to target low threshold spiking interneurons with a high connectivity in the MEC, making them a distinct projection compared to PV^+^ cells of the MS [@fuchs_local_2016]. However, there is evidence from the rat suggesting that CB^+^ is not a marker selectively expressed in GABAergic cells of the MS [@unal_synaptic_2015]. A substantial proportion of cells ($15\%$) express ChAT suggesting that these cells could potentially belong to a population of cells capable of GABA/ACh co-release. Therefore, more experiments addressing discrepancies between rat and mouse, but also between interneuron cell types, might be required.

One concern of a direct septal stimulation is that PV^+^ cells in the MS are not a homogeneous group, fire at different phases of the $\theta$ cycle and might not be $\theta$ modulated under physiological conditions [@borhegyi_phase_2004; @joshi_behavior-dependent_2017; @unal_synaptic_2015]. Indeed, some PV^+^ cells of the MS express HCN channels, making them more prone to fire bursts or to being active during $\theta$ periods [@hangya_gabaergic_2009; @varga_presence_2008]. In this study, I have shown that optogenetically identified PV^+^ MS cells show different phase preferences (Figure \@ref(fig:UnitDiversity)C and D) which could result in an out of phase activation during optical stimulation. A failure of $\theta$ entrainment in immobile mice and data from freely moving mice and rats suggests that fibre stimulation under different state conditions is reliable and results in similar entrainment, supporting the notion of an overall significance for PV^+^ projections [@lepperod_optogenetic_2021; @schlesiger_two_2021].

Up to this point, not enough data is available to establish excitatory drive from cholinergic projections of the MS to the PaS or MEC and how they might be able to modulate the network. Such data could prove useful, providing further insights into how the MS might set the network state and entrain $\theta$ in cortical areas.

## Implications for memory

In the experiments shown here, I have demonstrated that local PaS interneurons were specifically targeted by GABAergic projections from the MS and that the activation of MS interneurons generated entrainment even in the slow $\gamma$ frequency band. It was shown in a mouse model of alzheimer's disease that $\theta$-$\gamma$ coupling is explicitly impaired, resulting in deficits during spatial learning [@etter_optogenetic_2019]. An intervention using PV^+^ cell stimulation in the MS, however, could rescue the deficits and improve learning to the level of wildtype mice. With the known loss of cholinergic cells in alzheimer's disease [@davies_selective_1976], the fact that not only a behavioural improvement, but also the recovery of coupling between $\theta$ and $\gamma$ was detected, underlines the potential involvement of synaptic summation achieved by synchronisation. With the identification of septal targets in the PaS and the resulting outputs to the MEC, I offer a potential mechanism by which this coupling could be achieved. A synchronisation of $\theta$ along the parahippocampal axis is accomplished by disinhibition and phase locking of interneuron activity, leading to an environment primed for STDP. FS interneurons present themselves as a primary target and can generate local $\theta$-$\gamma$ coupling in cortical areas [@cardin_driving_2009; @sohal_parvalbumin_2009]. Hence, deficits in interneuron entrainment could impair memory formation. Cholinergic projections of the MS, on the other hand, might support such integration of information in the cortex via disinhibition of FS cells and increased overall inhibition driven by layer I interneurons. Such a reduction in local network activity allows for an increased focus on excitatory external inputs. Additionally, I hypothesise that cholinergic modulation of pyramidal cells in the PaS and MEC can further mediate synaptic integration and support memory formation [@caruana_stimulation_2004; @glasgow_cholinergic_2012]. This hypothesis is supported by data from the CA1 where previous activation of the MS led to a muscarinic dependent increase of long term potentiation (LTP) at the basal dendrites [@ovsepian_endogenous_2004]. This can be observed in running rats but will be absent during immobility [@leung_cholinergic_2003], underlining the importance of cholinergic cells during behavioural states [@mamad_medial_2015; @vandecasteele_optogenetic_2014]. Interactions between cholinergic MS cells and GABAergic MS cells are known to be especially important for higher memory load [@roland_medial_2014], suggesting that an orchestrated interaction of cholinergic modulation and excitation with GABAergic inhibition by cells of the MS could play a crucial role in memory function.

Another study by @jacob_medial_2017 revealed that a temporal inactivation of the MS using muscimol (GABA~A~ agonist shutting down local activity) or lesions in the MEC will impair spatial learning and distance estimation. This was tested by rats learning to associate a reward zone at a fixed distance without visual cues. Further, it was shown that $\theta$ in the MEC was abolished during MS inactivation. They hypothesised that the MS and MEC are crucial in learning distances to a reward, which can be impaired by loss of MS or MEC function. This suggests that coding for the reward zone could be mediated by septal-parahippocampal interactions and synchronisation. Evidence supporting the importance of the MS for learning distance estimation were also found in humans where hippocampal $\theta$ bursts -- correlated to the distance to an object -- could be observed before navigating to a target location visited in the past, suggesting a connection to memory retrieval [@bush_human_2017]. The MEC and the parahippocampal formation are major cortical inputs to the hippocampus [@kohler_intrinsic_1985; @witter_topographical_1989], which are important for the temporal organisation of spiking [@schlesiger_medial_2015]. Therefore, setting the phase between hippocampus and MEC via the PaS by MS neurons might allow for memory formation through an increased probability of simultaneous inputs [@adoff_functional_2021; @dickson_enhancement_2002]. Addressing whether modulation of MS cells could actively change distance estimation and learning of associations between reward and locations will play a crucial role in understanding the importance of the MS and PaS in spatial memory.

## Limitations of the study and Outlook

Despite the insights gained into $\theta$ generation and parahippocampal circuits, there were some limitations to these experiments which should be addressed in the future. As previously discussed, recording the LFP in immobile animals in a resting state will result in less activity in the parahippocampal formation. While such an approach gives complete control over MS projections without interference of simultaneous activation of different proportion of septal cells, I was able to show that modulation of parahippocampal network activity by inhibition likely requires a basic level of parahippocampal activity. Similar findings were reported for experiments investigating cholinergic septal projections [@mamad_medial_2015; @vandecasteele_optogenetic_2014], where behavioural states can mask potential functions. Therefore, it might be important to investigate MS GABAergic projections in other behavioural states by designing tasks in freely moving animals or in head fixed animals in virtual reality (VR). This would allow for the same animal to be recorded during movement and immobile periods, capturing the contribution of behaviours.

Another limitation concerns channelrhodopsin which, depending on the variant, will show differences in reliability during different stimulation frequencies [@lin_users_2011]. Here, we used a variant (*hChR2(H134R)*) -- which for our purposes of stimulation in the $\theta$ band -- was sufficient but might be less reliable at frequencies over $25\ Hz$ [@lin_characterization_2009]. Therefore, to further investigate a potential $\theta$-$\gamma$ coupling with optogenetic tools, faster variants should be considered. Additionally, a modulation through the activation of septal projections might not be sufficient to understand function [@carpenter_modulating_2017]. Hence, new inhibitory tools could be used to address shortcomings from activation using reversible deactivation of synaptic release [@bernal_sierra_potassium_2018].

Similarly, some limitations occur for the *in-vitro* experiments, such as potential masking of muscarinic effects during whole-cell recordings due to wash out. Small changes could be amplified by using different intracellular solutions containing caesium and holding the cell at positive potentials. This would allow for improved detection of a hyperpolarisation via muscarinic receptors and could unmask hidden depolarisations occurring simultaneously with hyperpolarisations.

With new insights from this study, new questions can be addressed. Future experiments should address the role of the MS and PaS interactions in the context of spatial memory [@kesner_neural_1998; @liu_excitotoxic_2001; @pang_damage_2010; @poucet_septum_1990]. A task based on @jacob_medial_2017 was used in a VR setting [@tennant_stellate_2018] and could be utilised to investigate the role of GABAergic projections during distance estimation. Such an approach could address whether GABAergic long-range projections can synchronise activity in the PaS and MEC in order to learn reward locations, or their involvement in path integration [@etienne_path_2004]. Path integration describes a strategy to estimate distances by integrating over the distances already travelled. This computation is thought to require different inputs such as self motion detection, including speed or acceleration and direction. Speed can control $\theta$ power [@mcfarland_relationship_1975] and acceleration was recently shown to be affected by the $\theta$ frequency [@kropff_frequency_2021]. @tennant_stellate_2018 has shown that, on a treadmill, animals will use motor information even when provided visual cues, suggesting a preferred method of integration. The MS, as already shown by @jacob_medial_2017, is well-positioned to relay movement information [@king_rhythmicity_1998; @zhou_comparison_1999], whereas the PaS, with a high density of GABAergic fibres from the MS as major output to the MEC, could significantly contribute to computation.

<!-- ## MS in speed and distance coding -->

<!-- The MS was found to have several cells coding for speed #king#zhou99 and as we discussed before activation can drive or reduce the locomotion of an animal #justus#fuhrmann. It is long known that $\theta$ activity of the MS and the hippocampus correlate with speed #vanderwolf and cells modulated by speed can be found not only in the MS but in the MEC as well ###sargolini#kropf. The implication of Recently a link from the pedunculopontine tegmental nucleus was identified as a driving force behind such locomotion and is mediated by the medial septum and the diagonal band of Broca #carvalho. Speed cells can be excited or inhibited through this pathway but are more likely interneurons.   -->

<!-- Another lesion study by @jacob_medial_2017 revealed that lesion of the MS will impair spatial learning. To test this rats were trained to run a linear track and stop at a visually indicated distance to receive a reward. After removing the visual cue rats were able to estimate the distance correctly, however, showed an increased error in estimation when the MS or the MEC were lesioned. A lesion in the hippocampus on the other hand showed no significant loss in accuracy. Findings supporting the importance of the MS for distance estimation were found in humans where $\theta$-bursts could be observed before navigating to a target location. The observed bush et al  -->

<!-- but new evidence suggests that at least in the MEC information of the LFP does not relate to speed directly but to acceleration.  -->

## Conclusion

In the present study, I have demonstrated that PV^+^ and ChAT^+^ septal projection patterns to the PaS are similar to MS projections to the MEC, suggesting that projection patterns are mainly conserved throughout the parahippocampal network. They can exhibit nuanced differences such as involvement of layer I cells -- a distinct group of interneurons -- in inhibitory regulation of the network, or reduced activation of pyramidal cells through acetylcholine. We have provided further evidence that GABAergic MS cells play a major role in organising oscillatory activity in the $\theta$ and $\gamma$ band in the PaS and MEC, but rely on an excitatory drive from up-stream regions to entrain local circuits via disinhibition. Whether the excitatory state of the network can be accomplished by the MS itself through cholinergic modulation during behavioural states or if inputs from the hippocampus are required, remains to be shown. By revealing new targets and the required network state interactions in the MS-parahippocampal axis, we have provided further insights into understanding parahippocampal synchronisation and organisation. These insights provide the basis for new ideas for future projects, which could lead to a better understanding of parahippocampal computation and memory.

<!-- ---------------- -->

<!-- On a technical level new tools are available to understand the brain a bit better. This also includes ways of analysing data and to estimate properties of different measurements. In the past, until the beginning of the 20th century, Bayes' theorem was used at large to estimate parameters in astrology ###Gauss and other notions of events. However, the use of Bayes' theorem came out of fashion with Fisher establishing the nowadays know frequentist hypothesis testing due to the fact that more complex problems could be solved easier using maximum likelihood estimation [@aldrich_r_1997]. This changed over the last decades with the implementation of Markov chain Monte Carlo simulations on modern computers. More complex issues can again be framed in Bayes' theorem without solving manually for complex derivatives which can become more difficult in higher parameter space and might be impossible to do by hand [@carpenter_stan_2015]. The interpretation of estimates derived using Bayes' give a complete distribution for the estimates allowing to quantify uncertainty using credible intervals. -->

<!--  Interestingly enough, bats do not show a classical $\theta$ pattern during exploration [@eliav_nonoscillatory_2018] -->

<!-- - speed code of cells is affected when blocking mec pv cells with cno and reduced grid scores -->

<!-- ### excitatory inputs can be supressed by acetylcholine -- both in PaS and MEC (#Hamam07,#barrett#Sparks#glasgow12) -->

<!-- ### layer 2 neurons can be depolarised by muscarinic activation in PaS #Glasgow13 -->

<!-- Similarly to the MEC the show some rebound properties indicated by a decreased sag-ratio. This -->

<!-- Cell Type count: -->

<!-- This is expected considering that the majority of the cells in the PaS are WFS1 positive and only a fraction of the PaS are interneurons [@sammons_electrophysiological_2019]. -->

<!-- sag ratio in DS -- oscillations as in stellate cells --more likely than in interneurons discuss chapman -->

<!-- L1 cells are a funcitionally distinct group of IN in the PaS. Func -->

<!-- - Gerashchenko 2001 show that lesion of PV cells and ChAT cells reduce theta power in Hippocampus and cortex -->

<!-- - difference to MEC -->

<!-- - what does the PaS add to functional output -->

<!-- - no visible difference in theta between MEC and PaS -- explanation  -->

<!-- The activation of the MS lead to an increase of $\rho$ during the stimulation period and dropped off quickly after the stimulation was finished.  -- no entraining of LFP for longer -- see fuhrmann et all for contrast -->

<!-- cholinergic cells don't fire in theta in the MS and are more likely to increase -->

<!-- toth show projections from hippocampus to MS -->

<!-- bender15 shows that MS PV can entrain theta in hippocampus -->

<!-- $\theta$ frequency of PV^+^ septal fibres projecting to the hippocampus can reduce running speed ###Bender2015. Further, it did not change spatial firing patterns, nor did it change the firing frequency of hippocampal cells. -->

<!-- - PV projections are important but require excitatory drive in the target region -->

<!-- - can be due to a synchronised upstream region such as the hippocampus -- then PV cells might be able to improve phase timing of PaS -->

<!-- - under lines crucial role of MS which manages on global scale timing which could be important for computation downstream by synchronising events -->

<!-- - PaS is positioned in a way that it is important for the MEC due to large fraction of projections target MEC cells -- glutamergic drive downstream and again regulated by MS to improve timing -->

<!-- - therefore drive can move downstream without losing accuracy of original synchronising signal of MS -- allows small region to entrain theta globally -->

<!-- - PaS has especially many glutamergic cells in a high density package -- distribution of drive on dorsal ventral axis? -->

<!-- Furthermore, an inactivation of the MS in rats using lidocaine or muscimol will not only lead to reduced $\theta$ activity but also to reduced grid cell stability in the MEC and destabilise place fields in the hippocampus [@brandon_new_2014; @koenig_spatial_2011]. Head-direction cells on the other hand were not significantly effected. Recently, @lepperod_optogenetic_2021 showed in rats that activation of PV^+^ cells in the MS could drive LFP in the MEC, reduced $\theta$ and phase precession in grid cells but did not abolish grid cell stability. Furthermore, it was shown that speed modulation which normally occurs in the MEC [@gonzalez-sulser_grid_2017] was only disrupted on the cell LFP level due to MS stimulation, but not on the cell level. -->

<!-- --- make point that this distance learning can be done via phase coding etc -->

<!-- Another lesion study by @jacob_medial_2017 revealed that lesion of the MS will impair spatial learning. To test this rats were trained to run a linear track and stop at a visually indicated distance to receive a reward. After removing the visual cue rats were able to estimate the distance correctly, however, showed an increased error in estimation when the MS or the MEC were lesioned. A lesion in the hippocampus on the other hand showed no significant loss in accuracy. Findings supporting the importance of the MS for distance estimation were found in humans where $\theta$-bursts could be observed before navigating to a target location. The observed bush et al  -->
