--- 
title: "Functional Role of Medial Septal Projections to the Parasubiculum"
author: "Daniel Parthier"
date: "28.09.2021"
documentclass: book
classoption: openany
fontsize: 12pt
papersize: a4
geometry: left=3cm, right=3cm, top=2.5cm, bottom=2.5cm
linestretch: 1.5
link-citations: yes
mainfont: URW Nimbus Roman
bibliography:
- book.bib
- packages.bib
#- references.bib
 #WholeLibrary.bib
- Thesis.bib
csl: the-journal-of-neuroscience.csl
sansfont: URW Nimbus Roman
site: bookdown::bookdown_site
subtitle: |
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | &nbsp;
  | Inaugural-Dissertation
  | to obtain the academic degree
  | Doctor rerum naturalium (Dr. rer. nat.)
  |
  | submitted to the Department of Biology, Chemistry and Pharmacy
  | of Freie Universität Berlin
  | by
biblio-style: apalike
# toc-depth: 3
output:
    pdf_document2:
      extra_dependencies: ["flafter"]
      toc: no
    citation_package: biblatex
    keep_tex: yes
    biblatexoptions: [backend=biber, maxbibnames=999]
indent: true
header-includes:
- \AtBeginDocument{\frontmatter}
---
\pagenumbering{gobble} 
\newpage

\topskip0pt
\vspace*{\fill}
\noindent
The experimental work of this thesis was conducted between August 2016 and June 2021 under the supervision of Prof. Dr. Dietmar Schmitz at the Neuroscience Research Centre (NWFZ) of the Charité.
\vspace*{\fill}

*1^st^ reviewer: Prof. Dr. Dietmar Schmitz*

*2^nd^ reviewer: Prof. Dr. Mathias F. Wernet*

\vspace{1cm}
\hspace{0pt}
*Date of disputation:*
\hspace{0pt}
\clearpage

# Acknowledgements {-}
First and foremost, I would like to thank my doctoral supervisor Prof. Dietmar Schmitz for his continuous support and advice. I would especially like to thank him for encouraging me to find my own strengths and am grateful for the opportunity to follow my interests in his lab.

Thanks to Prof. Mathias F. Wernet for agreeing to be my second reviewer.

I would like to thank John Tukker for his support, all the idea-sparking discussions over the years, and the time he took to help me to learn more about all the *in-vivo* work.

Thanks to Alexander Stumpf and Rosanna Sammons for helping with some of the recordings that could sometimes feel long, but were more fun together.

Further, I would like to thank Constance Holman, Noam Nitzan and Hung Lo who made the common struggles a little bit more enjoyable and helped to anticipate success. Laura Moreno-Velasquez, Felicitas Brüntgens for wonderful breaks and encouragement throughout the years. Furthermore, I am grateful to Nikolaus Maier and Friedrich Johenning for all the vivid discussions and inputs from day one.

Special thanks to Anke Schönherr, Susanne Rieckmann, and Katja Czieselsky, for keeping everything running and making life for everyone in the lab easier.

I thank all the members of the Schmitz-Lab for all the discussions, the great work environment, and also the lively social events.

My family, who have always been supportive and helped me to become the person I am today.

Finally, Lisa, who was always there for me during challenging times and without whom nothing of this would have been possible. I will always be grateful.


# Abstract {-}
<!-- Oscillations arise in the brain through changes induced by population activity, synaptic inputs and the resulting membrane potential changes. They can indicate synchronicity and communication between areas.  -->
\pagenumbering{Roman}

Oscillations are a hallmark of brain activity and can be generated by local synchronisation-mechanisms. They have been implicated in the communication between brain areas.
An important type of oscillations are $\theta$ oscillations ($4$-$12\ Hz$), which are associated with different behaviours, such as movements and navigation, but they also play a crucial role in memory formation and retrieval.
One of the major $\theta$ rhythm generators in the brain is the medial septum (MS), which with its different types of projecting neurons, innervates many cortical areas and synchronises their activity. 
I investigated two major projection types of the MS: GABAergic ($\gamma$-aminobutyric acid -- GABA) and  cholinergic (acetylcholine -- ACh) projections.
Both projections are known to target the medial entorhinal cortex (MEC) and hippocampus.
Parvalbumin positive (PV^+^) projections of the MS, which are GABAergic, are known to synchronise cortical networks via disinhibition often by inhibiting interneurons.
In contrast, cholinergic projections of the MS project to a wide range of cell types in the MEC and hippocampus and can have substantially different effects on the target cell (e.g. activation or inhibition). 
Thus, their function on a network can range from increasing activity through depolarising excitatory cells, to more inhibition of the network by activating interneurons, or even modulating synaptic integration. 
Previous studies have focussed on identifying projections to the hippocampus and the MEC but did not consider the parasubiculum (PaS), a major input of the MEC. In this study, we electrophysiologically characterised cells in the PaS and demonstrated layer I interneurons to be distinctly different from putative layer II interneurons.
The PaS, with its strong $\theta$ rhythmic firing cells, was shown to have the highest density of MS PV^+^ fibres in the parahippocampal formation, suggesting that it is an important target of MS projections and yet MS inputs to the PaS are unknown. 
Using channelrhodopsin (ChR2), a light sensitive ion channel, expressed in the MS of PV-Cre and ChAT-Cre (choline acetyltransferase) mice *in-vivo*, I identified GABAergic and cholinergic MS connections to the PaS *in-vitro* and demonstrated cell type specific projection patterns. 
I found that PV^+^ MS projections mainly inhibit interneurons in the PaS, including layer I interneurons, representing a novel cortical target of PV^+^ MS cells. On the other hand, cholinergic projections depolarise layer I interneurons and have multiple effects on deeper cells of the PaS, leading to a depolarisation or hyperpolarisation.
To investigate a potential role of GABAergic projections in $\theta$ generation, I recorded local field potentials (LFP) in awake head-fixed mice and entrained oscillations in the PaS by stimulating with light in the MS.
In contrast, local stimulation of fibres in the PaS could not entrain oscillation, suggesting that increased activity in the PaS might be required for MS PV^+^ cells to entrain $\theta$. 
Taken together, stimulation of PV^+^ cells in the MS is sufficient to drive oscillations in the PaS, likely via disinhibition in line with other areas as the MEC and hippocampus. However, novel targets in layer I could be involved via cholinergic activation and GABAergic entrainment. Whether cholinergic activation by itself can entrain $\theta$ remains to be further investigated.

<!-- Taken together, newly found targets in the layer I of the PaS could provide new mechanisms used by the MS to entrain $\theta$ and, as the failed entrainment during fibre stimulation shows, entrainment might require an active network state. -->



# Zusammenfassung {-}
Oszillationen sind ein Kennzeichen von Gehirn entstehen und können durch lokale Synchronisationsmechanismen generiert werden. Sie spielen eine wichtige Rolle bei der Kommunikation zwischen Gehirnarealen.
Ein wichtiger Typ von Oszillationen sind $\theta$ Oszillationen ($4-12\ Hz$), welche mit verschiedenen Verhalten wie Bewegung und Navigation assoziiert sind und eine wichtige Rolle in der Gedächtnisbildung und -abrufung spielen. 
Einer der wichtigen $\theta$ Generatoren im Gehirn ist das Mediale Septum (MS), welches mit seinen verschiedenen projizierenden Neuronen viele kortikale Regionen innerviert. 
Ich habe zwei Typen von Projektionen des MS untersucht: GABAerge ($\gamma$-Aminobuttersäure -- GABA) und cholinerg (Acetylcholin -- ACh) Projektionen. Beide Type projizieren zum Medialen Entohinalen Kortex (MEC) und zum Hippocampus. Parvalbumin positive (PV^+^) Projektionen des MS können kortikale Netzwerke via Disinhibition, durch inhibieren von Interneuronen, synchronisieren. Im Gegensatz dazu projizieren cholinerge Projektionen des MS zu verschiedensten Zelltypen des MEC und des Hippocampus und können unterschiedliche weitreichende Effekte auf Zellen haben (z.B. Aktivierung und Inhibierung). Folglich können die Konsequenzen von Aktivierung des Netzwerkes via Depolarisation von exzitatorischen Zellen, über Inhibierung des Netzwerkes via Aktivierung von Interneuronen bis hin zur Modulation von synaptischer Integration reichen. 
In der Vergangenheit haben Studien sich auf die Identifizierung von Projektionen zum Hippocampus und MECs fokussiert, jedoch nicht zum Parasubiculum (PaS), eines der bedeutendsten Eingänge des MEC. In dieser Studie haben wir elektrophysiologisch Zellen im PaS charakterisiert und konnten herausstellen, dass Schicht I Zellen sich von anderen vermeintlichen Interneuronen in Schicht II unterscheiden.
Das PaS, mit seinen im $\theta$ Rhythmus feuernden Zellen, hat die höchste Dichte von MS PV^+^ Fasern im parahippocampalen Netzwerk, was es als besonderes Ziel für MS Projektionen herausstellt. Dennoch sind Projektionen vom MS zum PaS nicht untersucht worden. Mit Hilfe von Channelrhodopsin (ChR2), einem lichtsensitivem Ionenkanal, welcher im MS von PV-Cre und ChAT-Cre Mäusen exprimiert wurde, konnten ich GABAerge und cholinerge MS Verbindungen zum PaS *in-vitro* detektieren und Zelltyp-speziefische Projektionen identifizieren.
Ich konnte herausstellen, dass PV^+^ MS Projektionen hauptsächlich Interneurone im PaS inhibieren. Insbesondere Schicht I Interneurone stellen ein neues kortikales Ziel von PV^+^ MS Zellen dar. Im Gegensatz dazu werden Schicht I Interneurone des PaS durch cholinerge MS Projektionen depolarisiert wohingegen Zellen in tieferen Schichten depolarisiert oder hyperpolarisiert werden können. 
Um zu zeigen, dass man mit GABAergen Projektionen $\theta$ generieren kann, nahm ich das lokale Feldpotential (LFP) in Kopf-fixierten Mäusen auf und fanden, dass man Oszillationen mit MS-Stimulation gleichschalten kann, jedoch eine Stimulation der Fasern im PaS nicht ausreichend ist. Das weist darauf hin, dass eine erhöhte PaS-Aktivität notwendig ist, um $\theta$ Oszillationen im PaS zu generieren Zusammenfassend zeigt sich, dass eine Stimulation der PV^+^ Zellen im MS ausreichend ist, um im PaS Oszillationen zu generieren. Disinhibierung im PaS ist, ähnlich wie auch im MEC und Hippocampus, ein wahrscheinlicher Mechanismus. Weiterhin könnten jedoch neue Ziele von cholinergen und GABAergen Fasern in Schicht I bei der $\theta$ Generierung involviert sein. Ob $\theta$ Oszillationen durch cholinerge Projektionen gleichgeschaltet werden kann muss jedoch noch durch weitere Studien gezeigt werden.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'data.table'
), 'packages.bib')
knitr::opts_chunk$set(dev = 'pdf', echo = FALSE, warning = FALSE, message = FALSE, fig.pos = "htbp")
#knitr::opts_chunk$set(dev = 'png', echo = FALSE, warning = FALSE, message = FALSE, dpi = 600, fig.pos = "!htb")
library('magrittr')
library('png')
library('ggh4x')
library('ggplot2')
library('data.table')
library('patchwork')
library('knitr')
library('kableExtra')
library('readxl')

InputParameters <- readRDS(file = "Data/InputParameters.rds")
ParameterCompTable <- readRDS(file = "Data/ParameterComparisons.rds")
CellChar <- readRDS(file = "Data/CellChar.rds")
source("RScripts/ParPostProcessing.R")
source("RScripts/PlotFunctions.R")

ParameterCompTable[,`non-zero`:="",][OutOfInterval==1,`non-zero`:="yes",]
setnames(x = ParameterCompTable, old = c("GroupComparison"), new=c("Comparison"))
setorder(ParameterCompTable, "Parameter")

#### input onset PV
testDataOnset <- InputParameters[!is.na(PulseTime)&Drug==F&Mouseline=="PV",,]
testDataOnset[,RowID:=.I,]
testDataOnset[,CellTypeMouse := paste0(Mouseline,CellType),]
testDataOnset <- testDataOnset[Onset>0&!grepl(pattern = "blocked by NBQX", x = Comment)&PulseNr==1,]
testDataOnset <- testDataOnset[Cell!="160810_5_RSadjn"&abs(PeakAmp)>3*BaselineSD,][(Clamp=="CC"&abs(PeakAmp)>0.2)|(Clamp=="VC"&abs(PeakAmp)>5),]
InputOnsets <- testDataOnset[,.N,by=.(CellType)]
InputOnsetsCells <- testDataOnset[,.(.N, unique(Cell)),by=.(CellType)][,.N,by=CellType]

#### log ods comparison connectivity
LogOddsCompConnectivity <- readRDS(file = "Data/HDILogOddsComparison.rds")
LogOddsCompConnectivity[,Comparison:=GroupComparison,]
LogOddsCompConnectivity[!grepl(pattern = "ChAT", x = GroupComparison), MouseLine:="PV",][!grepl(pattern = "PV", x = GroupComparison), MouseLine:="ChAT",][is.na(MouseLine),MouseLine:="Cross",]


HDIEx <- function(x, digits=2) {
    x[,paste0("$[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$"),]
}
HDItxt <- function(x, digits=2, unit="") {
  x[,paste0("$", trimws(format(round(`50%`, digits = digits), nsmall = digits)),"\\ ",unit,"$ $[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$"),]
}
HDICt <- function(x, digits=2, unit="", sig="only") {
  if(any(grepl(pattern = "Cell Type",names(x)))) {
  x[,paste0(`Cell Type`,": $" , trimws(format(round(`50%`, digits = digits), nsmall = digits)),"\\ ",unit,"$ $[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$", collapse = ", "),]
  } else   if(any(grepl(pattern = "Comparison",names(x)))) {
  switch (sig,
    "only" = {Select <- 1},
    "no" = {Select <- 0},
    "all" = {Select <-c(0,1)},
  )
  ComparisonString <- grep(pattern = "Comparison",names(x), value = T)
  x[OutOfInterval%in%Select,paste0(get(ComparisonString),": $" , trimws(format(round(`50%`, digits = digits), nsmall = digits)),"\\ ",unit,"$ $[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$", collapse = ", "),]
}
}
HDISummary <- function(x, digits=2, unit="", sig="all") {
  if(any(grepl(pattern = "Cell Type",names(x)))) {
  x[,paste0(GroupComparison,": $" , trimws(format(round(`50%`, digits = digits), nsmall = digits)),"\\ ",unit,"$ $[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$", collapse = ", "),]
  } else   if(any(grepl(pattern = "Comparison",names(x)))) {
  switch (sig,
    "only" = {Select <- 1},
    "no" = {Select <- 0},
    "all" = {Select <-c(0,1)},
  )
  x[OutOfInterval%in%Select,paste0(GroupComparison,": $" , trimws(format(round(`50%`, digits = digits), nsmall = digits)),"\\ ",unit,"$ $[",trimws(format(round(`2.5%`, digits = digits), nsmall = digits)),"; ", trimws(format(round(`97.5%`, digits = digits), nsmall = digits)),"]$", collapse = ", "),]
}
}



```
